MQCONNECTION_FAILED = 20001
MESSAGE_RETRIEVE_FAILED = 20002
QUEUE_NOT_FOUND = 20003
MESSAGE_NOT_FOUND = 20004
ACCEPTED_HISTORY_MESSAGE = "Accepted during Manual Moderation"
REJECTED_HISTORY_MESSAGE = "Rejected during Manual Moderation"
